server:
  port: 8080
  allowOrigins:
    - "*"
  bodyLimit: "10M" # MiB
  timeout: 30 # Seconds
 
jwt:
  accessSecretKey: "ygCaByqqgq4QJeBQ"
  refreshSecretKey: "XgMfYJYrKRrcCVrE"
  accessExpires: 86400 # Seconds
  refreshExpires: 604800 # Seconds
  
database:
  host: localhost
  port: 5432
  user: postgres
  password: 565655
  dbname: hocadb
  sslmode: disable
  schema: public