server:
  port: 8080
  allowOrigins:
    - "*"
  bodyLimit: "10M" # MiB
  timeout: 30 # Seconds
 
oauth2:
  userRedirectUrl: "http://localhost:8080/v1/oauth2/google/user/login/callback"
  clientId: "760404231944-8t64vutimelm5hpliaulfur6a657pdet.apps.googleusercontent.com"
  clientSecret: "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"
  endpoints:
    authUrl: "https://accounts.google.com/o/oauth2/auth?access_type=offline&approval_prompt=force"
    tokenUrl: "https://oauth2.googleapis.com/token"
    deviceAuthUrl: "https://oauth2.googleapis.com/device/code"
  scopes:
    - "https://www.googleapis.com/auth/userinfo.email"
    - "https://www.googleapis.com/auth/userinfo.profile"
  userInfoUrl: "https://www.googleapis.com/oauth2/v2/userinfo"
  revokeUrl: "https://accounts.google.com/o/oauth2/revoke"

google:
  apiKey: "AIzaSyCbMPxtX2B1eKnInkkMfg77DiLj_7P8ob4"

minio:
  bucketEndpoint: "minio.bsthun.com"
  bucketName: "cs-hoca"  

scb:
  scbUrl: "https://api-sandbox.partners.scb/partners/sandbox"
  scbAppKey: "l720fad5e9e8fb43519658c675172dee17"
  scbAppSecret: "2c77d759feb54b0c85ee7534609e12d5"
  scbBillerId: "390623901403238"

database:
  host: localhost
  port: 5432
  user: postgres
  password: 565655
  dbname: hocadb
  sslmode: disable
  schema: public